# Data Preprocessing

## Objective

This notebook performs preprocessing of the raw TCGA gene expression dataset before exploratory analysis and downstream machine learning.

The preprocessing workflow includes:

- Loading raw gene expression and sample labels
- Checking dataset structure
- Validating missing values
- Ensuring sample-label alignment
- Separating expression features and classification labels
- Saving cleaned datasets for downstream analysis

The processed datasets generated here are used in subsequent EDA and feature engineering workflows.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
expression_df = pd.read_csv(
    "../data/raw/data.csv",
    index_col=0
)

expression_df.head()

,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.0
sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.0
sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.0
sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.0
sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.0

In [3]:
labels_df = pd.read_csv(
    "../data/raw/labels.csv"
)

labels_df.head()

  Unnamed: 0 Class
0   sample_0  PRAD
1   sample_1  LUAD
2   sample_2  PRAD
3   sample_3  PRAD
4   sample_4  BRCA

In [4]:
print("Expression matrix shape:", expression_df.shape)
print("Labels shape:", labels_df.shape)

Expression matrix shape: (801, 20531)
Labels shape: (801, 2)

In [6]:
print(
    "Missing values in expression matrix:",
    expression_df.isnull().sum().sum()
)

print(
    "Missing values in labels:",
    labels_df.isnull().sum().sum()
)

Missing values in expression matrix: 0
Missing values in labels: 0

In [7]:
print(expression_df.index[:5])
print(labels_df["Unnamed: 0"].head())

Index(['sample_0', 'sample_1', 'sample_2', 'sample_3', 'sample_4'], dtype='object')
0    sample_0
1    sample_1
2    sample_2
3    sample_3
4    sample_4
Name: Unnamed: 0, dtype: object

In [8]:
sample_alignment = (
    expression_df.index == labels_df["Unnamed: 0"]
)

print("All samples aligned:", sample_alignment.all())

All samples aligned: True

In [9]:
X = expression_df.copy()

y = labels_df["Class"]

In [10]:
print("Feature matrix:", X.shape)
print("Labels:", y.shape)

Feature matrix: (801, 20531)
Labels: (801,)

In [11]:
processed_path = Path("../data/processed")
processed_path.mkdir(exist_ok=True)

In [12]:
X.to_csv(
    processed_path / "clean_expression_matrix.csv"
)

labels_df.to_csv(
    processed_path / "clean_labels.csv",
    index=False
)

print("Processed datasets saved.")

Processed datasets saved.

In [13]:
print(
    pd.read_csv(
        "../data/processed/clean_expression_matrix.csv",
        index_col=0
    ).shape
)

print(
    pd.read_csv(
        "../data/processed/clean_labels.csv"
    ).shape
)

(801, 20531)
(801, 2)